model_configs:
- !!python/object:gigantic_dataset.utils.configs.ModelConfig
    weight_path: ''  
    num_layers: 15  # in habrok should be 15
    nc: 32
    name: gatres
    act: relu # unfunctional
    has_final_linear: false # unfunctional

pe_config: 
    !!python/object:gigantic_dataset.utils.configs.PEConfig
    pe_technique: concat
    pe_init: "spe"
    pe_dim: 20
    pe_task: supervised
    aux_criterion: ''
    aux_loss_alpha: 0

lr: 0.0001
weight_decay: 0.00001
epochs: 1000
mask_rate: 0.95
criterion: mse
batch_size: 16  # this can be 120 in habrok
use_data_batch: true
device: cuda
norm_type:  znorm
task: semi
log_method: "wandb"
project_name: gida_model_improved_train #it is not auto-change when you eval(.)
save_path: '' # make it empty to auto-gen in a first training
log_per_epoch: 1
run_prefix: 'spe-transductive'  # to distinguish two wandb runs